security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login
            security: false

        secured:
            pattern:    ^/secured/
            form_login:
                check_path: /secured/login_check
                login_path: /secured/login
            logout:
                path:   /secured/logout
                target: /secured/

    access_control: ~